import { z } from "zod";

export const UnpromotedFE8Classes = [
  "Citizen",
  // "Dancer", // Dancer not implemented fully in LT
  "Myrmidon",
  "Mercenary",
  "Thief",
  "Recruit",
  "Soldier",
  "Knight",
  "Cavalier",
  "Pegasus Knight",
  "Journeyman",
  "Fighter",
  "Pirate",
  "Brigand",
  "Archer",
  "Monk",
  "Cleric",
  "Mage",
  "Shaman",
  "Troubadour",
  "Valkyrie",
  "Wyvern Rider",
  "Revenant",
  "Sword Wight",
  "Bow Wight",
  "Mogall",
  "Manakete",
] as const;

export const PromotedFE8Classes = [
  "Swordmaster",
  "Hero",
  "Rogue",
  "Assassin",
  "Paladin",
  "Great Knight",
  "Falcoknight",
  "General",
  "Berserker",
  "Sniper",
  "Bishop",
  "Ranger",
  "Warrior",
  "Sage",
  "Mage Knight",
  "Wyvern Lord",
  "Wyvern Knight",
  "Necromancer",
  "Sword Bonewalker",
  "Bow Bonewalker",
  "Entombed",
  "Arch Mogall",
] as const;

export type UnpromotedFE8Class = (typeof UnpromotedFE8Classes)[number];
export type PromotedFE8Class = (typeof PromotedFE8Classes)[number];

const FE8ClassesArray = [
  ...UnpromotedFE8Classes,
  ...PromotedFE8Classes,
] as const;

export const FE8ClassSchema = z.enum(FE8ClassesArray);
export type FE8Class = z.infer<typeof FE8ClassSchema>;

export const FE8ClassDescriptionMap: Record<FE8Class, string> = {
  Citizen: "A non-combatant civilian with no combat abilities.",
  // Dancer: "A support unit that can refresh an ally's turn by dancing.",
  Myrmidon: "A swift swordfighter with high crit potential.",
  Mercenary: "A balanced swordfighter with solid offense and defense.",
  Thief: "A nimble trickster able to pick locks and steal items.",
  Rogue: "An advanced thief with improved combat and lockpicking.",
  Recruit: "A trainee soldier with limited abilities and a bright future.",
  Soldier: "A lance-wielding foot unit, straightforward and unremarkable.",
  Cavalier: "A mounted unit with balanced stats and sword/lance access.",
  "Pegasus Knight": "A swift flying unit with high resistance but low defense.",
  Journeyman: "A young axe trainee who grows steadily with experience.",
  Fighter: "A strong but slower axe user with high HP and strength.",
  Warrior: "A promoted powerhouse proficient in axes (and sometimes bows).",
  Pirate: "An axe-wielding seafarer able to traverse water terrain.",
  Brigand: "An axe fighter adept at crossing rough terrain with ease.",
  Archer: "A ranged combatant specializing in bows and lacking melee.",
  Ranger: "A mounted archer with sword/bow capability and strong mobility.",
  Monk: "A light magic user focused on resisting dark arts.",
  Cleric: "A staff-wielding healer with limited offensive potential.",
  Mage: "An anima magic user excelling in magical offense.",
  Shaman: "A user of dark magic, slow but powerful in spells.",
  Troubadour: "A mounted healer using staffs to support allies.",
  Valkyrie: "A promoted troubadour adept with staves and light magic.",
  "Wyvern Rider": "A flying bruiser with high strength and defense.",
  Revenant: "A slow, weak undead monster that attacks with claws.",
  Entombed: "A stronger undead variant of the Revenant with higher stats.",
  "Sword Wight": "An undead swordsman with high skill and speed.",
  "Bow Wight": "An undead archer with fearsome long-range attacks.",
  Mogall: "A floating monster using dark magic with high resistance.",
  Swordmaster: "An expert swordsman with exceptional speed and crit rate.",
  Hero: "A balanced warrior strong with swords and axes.",
  Assassin: "A stealthy killer with a chance of instant-kill attacks.",
  Paladin: "A highly mobile mounted warrior with multiple weapon options.",
  "Great Knight": "A heavily armored mount using swords, lances, and axes.",
  Falcoknight: "A promoted Pegasus Knight with swords and lances.",
  Knight: "A heavily armored soldier boasting high defense but low movement.",
  General: "A promoted knight with even greater defense and multiple weapons.",
  Berserker: "An axe specialist with high crit potential.",
  Sniper: "A highly accurate archer specializing in ranged combat.",
  Bishop: "A promoted healer focusing on light magic and staff usage.",
  Sage: "A powerful mage proficient in anima magic and staves.",
  "Mage Knight": "A mounted mage with strong magic and higher mobility.",
  "Wyvern Lord": "A promoted Wyvern with immense strength and durability.",
  "Wyvern Knight": "A swift Wyvern variant with a deadly piercing attack.",
  Necromancer: "A dark caster capable of summoning phantoms.",
  "Sword Bonewalker": "An undead skeleton swordsman with cunning skill.",
  "Bow Bonewalker": "An undead skeleton archer specializing in ranged combat.",
  "Arch Mogall": "A highly resistant floating monster using dark magic.",
  Manakete: "A dragonkin unit with high stats and dragonstone breath attacks.",
};

export const FE8ClassToLTNidMap: Record<FE8Class, string> = {
  Citizen: "Citizen",
  // Dancer: "Dancer",
  Myrmidon: "Myrmidon",
  Mercenary: "Mercenary",
  Thief: "Thief",
  Rogue: "Rogue",
  Recruit: "Recruit",
  Soldier: "Soldier",
  Cavalier: "Cavalier",
  "Pegasus Knight": "Pegasus_Knight",
  Journeyman: "Journeyman",
  Fighter: "Fighter",
  Warrior: "Warrior",
  Pirate: "Pirate",
  Brigand: "Brigand",
  Archer: "Archer",
  Ranger: "Ranger",
  Monk: "Monk",
  Cleric: "Cleric",
  Mage: "Mage",
  Shaman: "Shaman",
  Troubadour: "Troubadour",
  Valkyrie: "Valkyrie",
  "Wyvern Rider": "Wyvern Rider",
  Revenant: "Revenant",
  Entombed: "Entombed",
  "Sword Wight": "Sword_Wight",
  "Bow Wight": "Bow_Wight",
  Mogall: "Mogall",
  Swordmaster: "Swordmaster",
  Hero: "Hero",
  Assassin: "Assassin",
  Paladin: "Paladin",
  "Great Knight": "Great_Knight",
  Falcoknight: "Falcoknight",
  Knight: "Knight",
  General: "General",
  Berserker: "Berserker",
  Sniper: "Sniper",
  Bishop: "Bishop",
  Sage: "Sage",
  "Mage Knight": "Mage Knight",
  "Wyvern Lord": "Wyvern Lord",
  "Wyvern Knight": "Wyvern Knight",
  Necromancer: "Necromancer",
  "Sword Bonewalker": "Sword_Bonewalker",
  "Bow Bonewalker": "Bow_Bonewalker",
  "Arch Mogall": "Arch_Mogall",
  Manakete: "Manakete",
};

